services:
  frontend:
    image: nginx:1.27-alpine
    cpus: 0.1
    mem_limit: 128m
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.stack-data/staticfiles:/app/staticfiles:ro
      - ./.stack-data/media:/app/media:ro
    depends_on:
      - backend

  backend:
    image: ghcr.io/matejstefanovski/delovna-proekt:latest
    cpus: 0.25
    mem_limit: 256m
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./.stack-data/staticfiles:/app/staticfiles
      - ./.stack-data/media:/app/media
      - ./.stack-data/db:/app/database
